jobs:
 - name: every3minutes
   targetName: dev 
   schedule: '*/3 * * * *'
   steps:
     - name: run models
       command: dbt run --models example.100kusd
       command: dbt run --models example.4599_system_note